Dropped Python 2 support
kobotoolbox/kobo-install pull request #134
Opened 2020-11-10 21:33 UTC by noliveleger

As title says:
Python 2 is dead, long live Python 2

2020-11-12 19:37 UTC, joshuaberetta requested changes
Some test still have some `__future__` imports:

```
tests/test_run.py
2:from __future__ import unicode_literals

tests/test_config.py
2:from __future__ import unicode_literals, absolute_import
```

2020-11-13 23:12 UTC, joshuaberetta requested changes

2020-11-13 23:12 UTC, joshuaberetta commented on tests/test_run.py
> +    builtin_open =
👀

2020-11-16 15:47 UTC, noliveleger commented on tests/test_run.py
> +    builtin_open =
😇

2020-11-16 18:43 UTC, joshuaberetta approved these changes

2020-11-16 19:20 UTC, merged